apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - service_account.yaml

images:
  - name: 598786118242.dkr.ecr.us-east-1.amazonaws.com/ask-bluej
    newTag: master_e8413e8
  - name: 598786118242.dkr.ecr.us-east-1.amazonaws.com/ask-bluej-backend
    newTag: master_a03c47b
