name: Approve Commit

on: commit_comment
jobs:
  approve-commit:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
    - name: apply approved status
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.comment.commit_id }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "state": "success",
          "context": "Commit reviewed and approved",
          "target_url": "https://github.com/${{ github.repository }}/commit/${{ github.event.comment.commit_id }}"
          }' \
        --fail
